// get
export const GET_ALLCOMPLETED_REQUEST = 'GET_ALLCOMPLETED_REQUEST';
export const GET_ALLCOMPLETED_SUCCESS = 'GET_ALLCOMPLETED_SUCCESS';
export const GET_ALLCOMPLETED_FAIL = 'GET_ALLCOMPLETED_FAIL';

export const GET_ALLINCOMPLETED_REQUEST = 'GET_ALLINCOMPLETED_REQUEST';
export const GET_ALLINCOMPLETED_SUCCESS = 'GET_ALLINCOMPLETED_SUCCESS';
export const GET_ALLINCOMPLETED_FAIL = 'GET_ALLINCOMPLETED_FAIL';

// post
export const POST_INCOMPLETED_REQUEST = 'POST_INCOMPLETED_REQUEST';
export const POST_INCOMPLETED_SUCCESS = 'POST_INCOMPLETED_SUCCESS';
export const POST_INCOMPLETED_FAIL = 'POST_INCOMPLETED_FAIL';

// put
export const UPDATE_COMPLETE_REQUEST = 'UPDATE_COMPLETE_REQUEST';
export const UPDATE_COMPLETE_SUCCESS = 'UPDATE_COMPLETE_SUCCESS';
export const UPDATE_COMPLETE_FAIL = 'UPDATE_COMPLETE_FAIL';

export const UPDATE_INCOMPLETE_REQUEST = 'UPDATE_INCOMPLETE_REQUEST';
export const UPDATE_INCOMPLETE_SUCCESS = 'UPDATE_INCOMPLETE_SUCCESS';
export const UPDATE_INCOMPLETE_FAIL = 'UPDATE_INCOMPLETE_FAIL';

// updates for complete -> incomplete vise versa
export const ADD_COMPLETE = 'ADD_COMPLETE';
export const REMOVE_COMPLETE = 'REMOVE_COMPLETE';

export const ADD_INCOMPLETE = 'ADD_INCOMPLETE';
export const REMOVE_INCOMPLETE = 'REMOVE_INCOMPLETE';

// DELETE
export const DELETEALL_SUCCESS = 'DELETEALL_SUCCESS';
